# Generated by Django 4.1 on 2022-08-13 09:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_joinuser_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='joinuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
