# Generated by Django 4.1 on 2022-08-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_joinuser_created_at_joinuser_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinuser',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='joinuser',
            name='updated_at',
        ),
    ]
