# Generated by Django 4.1 on 2022-09-03 22:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country_region', models.CharField(choices=[('UZBEKISTAN/TAS', 'Uzb'), ('RUSSIA/MOS', 'Rus'), ('USA/VAS', 'Usa')], default='UZBEKISTAN/TAS', max_length=25)),
                ('city', models.CharField(max_length=25)),
                ('zip_code', models.IntegerField(validators=[django.core.validators.MaxValueValidator(6, 'The higest zip_code is 6'), django.core.validators.MinValueValidator(1, 'The youngest zip_code is 1')])),
                ('number', models.IntegerField(validators=[django.core.validators.MaxValueValidator(13, 'The higest number is 13'), django.core.validators.MinValueValidator(5, 'The youngest number is 5')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
