# Generated by Django 4.1 on 2022-09-10 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('country_region', models.CharField(choices=[('Afghanistan', 'Af'), ('Åland Islands', 'Ax'), ('Albania', 'Al'), ('Algeria', 'Dz'), ('American Samoa', 'As'), ('AndorrA', 'Ad'), ('Angola', 'Ao'), ('Anguilla', 'Ai'), ('Antarctica', 'Aq'), ('Antigua and Barbuda', 'Ag'), ('Argentina', 'Ar'), ('Armenia', 'Am'), ('Aruba', 'Aw'), ('Australia', 'Au'), ('Austria', 'At'), ('Azerbaijan', 'Az'), ('Bahamas', 'Bs'), ('Bahrain', 'Bh'), ('Bangladesh', 'Bd'), ('Barbados', 'Bb'), ('Belarus', 'By'), ('Belgium', 'Be'), ('Belize', 'Bz'), ('Benin', 'Bj'), ('Bermuda', 'Bm'), ('Bhutan', 'Bt'), ('Bolivia', 'Bo'), ('Bosnia and Herzegovina', 'Ba'), ('Botswana', 'Bw'), ('Bouvet Island', 'Bv'), ('Brazil', 'Br'), ('British Indian Ocean Territory', 'Io'), ('Brunei Darussalam', 'Bn'), ('Bulgaria', 'Bg'), ('Burkina Faso', 'Bf'), ('Uzbekistan', 'Uz')], default='Uzbekistan', max_length=45)),
                ('city', models.CharField(max_length=25)),
                ('zip_code', models.CharField(max_length=6)),
                ('number', models.CharField(max_length=25)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('image', models.ImageField(default='media/images/avatar.png', upload_to='user-images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_image', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
