# Generated by Django 4.1 on 2022-08-22 21:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone_number',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(25, 'The max phone number length is 25'), django.core.validators.MinValueValidator(5, 'The min phone number length is 5')]),
        ),
    ]
